import { SettingSchemaDesc } from '@logseq/libs/dist/LSPlugin.user';

import { globals } from '../globals/globals';

interface PresetConfig {
    [key: string]: {
        [key: string]: string | number | boolean;
    };
}

export const presetsList: string[] = [
    'Solarized_default',
    'Logseq_original',
    'Mia_quattro',
    'Chocolate',
    'Custom',
    'Custom2',
    'Custom3'
];

export const fontsList: string[] = [
    'Fira Sans (theme default)',
    'Inter (Logseq default)',
    'Fira Code Nerd',
    'iA Writer Quattro',
    'Mulish',
    'OS System default'
];

export const presetsConfig: PresetConfig = {
    Solarized_default: {
        fontContentName: 'Fira Sans (theme default)',
        fontContentSize: '16px',
        fontUiSize: '13px',
        colorLightTitleText: '#009991',
        colorLightContentText: '#354145',
        colorLightContentTextBold: '#334247',
        colorLightContentTextItalic: '#354145',
        colorLightContentTextCode: '#CB4B16',
        colorLightLink: '#009991',
        colorLightLinkExt: '#B88726',
        colorLightTag: '#4C90B3',
        colorLightUiPanelsBg: '#EDE4D4',
        colorLightUiBodyBg: '#FEF8EC',
        colorLightContentBg: '#FEF8EC',
        colorLightContentPropsBg: '#F0E9DB',
        colorLightContentAltBg: '#F0E9DB',
        colorLightH1: '#354145',
        colorLightH2: '#354145',
        colorLightH3: '#354145',
        colorLightH4: '#354145',
        colorLightH5: '#354145',
        colorLightH6: '#354145',
        colorLightMarkBg: '#F9D86C',
        colorLightMarkText: '#334247',
        colorLightQuoteBg: '#D7EADD',
        colorLightQuoteText: '#334247',
        colorDarkTitleText: '#B88726',
        colorDarkContentText: '#AFB6B6',
        colorDarkContentTextBold: '#AFB6B6',
        colorDarkContentTextItalic: '#AFB6B6',
        colorDarkContentTextCode: '#2AA198',
        colorDarkLink: '#B88726',
        colorDarkLinkExt: '#738500',
        colorDarkTag: '#4C90B3',
        colorDarkH1: '#AFB6B6',
        colorDarkH2: '#AFB6B6',
        colorDarkH3: '#AFB6B6',
        colorDarkH4: '#AFB6B6',
        colorDarkH5: '#AFB6B6',
        colorDarkH6: '#AFB6B6',
        colorDarkUiPanelsBg: '#002933',
        colorDarkUiBodyBg: '#00323d',
        colorDarkContentBg: '#00323d',
        colorDarkContentPropsBg: '#073945',
        colorDarkContentAltBg: '#073945',
        colorDarkMarkBg: '#F9D86C',
        colorDarkMarkText: '#334247',
        colorDarkQuoteBg: '#223F3F',
        colorDarkQuoteText: '#AFB6B6',
        backgroundURLLight: 'lsp://logseq.io/logseq-awesome-styler/dist/img/bg.webp',
        backgroundURLDark: 'lsp://logseq.io/logseq-awesome-styler/dist/img/bg.webp',
        backgroundPadding: '20px 40px 20px 40px',
        backgroundShadow: true,
        bannersAsBackground: true,
        bannersIconGlow: true,
        contentMaxWidth: '1100px',
        contentWideMaxWidth: '1600px'
    },
    Logseq_original: {
        fontContentName: 'Inter (Logseq default)',
        fontContentSize: '16px',
        fontUiSize: '13px',
        colorLightTitleText: '#433F38',
        colorLightContentText: '#433F38',
        colorLightContentTextBold: '#433F38',
        colorLightContentTextItalic: '#433F38',
        colorLightContentTextCode: '#F7F7F7',
        colorLightLink: '#106BA3',
        colorLightLinkExt: '#106BA3',
        colorLightTag: '#106BA3',
        colorLightUiPanelsBg: '#F7F7F7',
        colorLightUiBodyBg: '#FFFFFF',
        colorLightContentBg: '#FFFFFF',
        colorLightContentPropsBg: '#F7F7F7',
        colorLightContentAltBg: '#F7F7F7',
        colorLightH1: '#433F38',
        colorLightH2: '#433F38',
        colorLightH3: '#433F38',
        colorLightH4: '#433F38',
        colorLightH5: '#433F38',
        colorLightH6: '#433F38',
        colorLightMarkBg: '#FEF4AE',
        colorLightMarkText: '#262626',
        colorLightQuoteBg: '#FBFAF8',
        colorLightQuoteText: '#433F38',
        colorDarkTitleText: '#A4B5B6',
        colorDarkContentText: '#A4B5B6',
        colorDarkContentTextBold: '#A4B5B6',
        colorDarkContentTextItalic: '#A4B5B6',
        colorDarkContentTextCode: '#A4B5B6',
        colorDarkLink: '#8ABBBB',
        colorDarkLinkExt: '#8ABBBB',
        colorDarkTag: '#8ABBBB',
        colorDarkUiPanelsBg: '#003642',
        colorDarkUiBodyBg: '#052B36',
        colorDarkContentBg: '#052B36',
        colorDarkContentPropsBg: '#083643',
        colorDarkContentAltBg: '#083643',
        colorDarkH1: '#A4B5B6',
        colorDarkH2: '#A4B5B6',
        colorDarkH3: '#A4B5B6',
        colorDarkH4: '#A4B5B6',
        colorDarkH5: '#A4B5B6',
        colorDarkH6: '#A4B5B6',
        colorDarkMarkBg: '#FEF4AE',
        colorDarkMarkText: '#262626',
        colorDarkQuoteBg: '#083643',
        colorDarkQuoteText: '#A4B5B6',
        backgroundURLLight: '',
        backgroundURLDark: '',
        backgroundPadding: '32px 32px 32px 32px',
        backgroundShadow: false,
        bannersAsBackground: false,
        bannersIconGlow: false,
        contentMaxWidth: '940px',
        contentWideMaxWidth: '100%'
    },
    Mia_quattro: {
        fontContentName: 'iA Writer Quattro',
        fontContentSize: '16px',
        fontUiSize: '13px',
        colorLightTitleText: '#1A1A1A',
        colorLightContentText: '#1A1A1A',
        colorLightContentTextBold: '#1A1A1A',
        colorLightContentTextItalic: '#1A1A1A',
        colorLightContentTextCode: '#747474',
        colorLightLink: '#0B82B9',
        colorLightLinkExt: '#0B82B9',
        colorLightTag: '#747474',
        colorLightUiPanelsBg: '#EAEAEA',
        colorLightUiBodyBg: '#F7F7F7',
        colorLightContentBg: '#F7F7F7',
        colorLightContentPropsBg: '#EAEAEA',
        colorLightContentAltBg: '#EAEAEA',
        colorLightH1: '#1A1A1A',
        colorLightH2: '#1A1A1A',
        colorLightH3: '#1A1A1A',
        colorLightH4: '#1A1A1A',
        colorLightH5: '#1A1A1A',
        colorLightH6: '#1A1A1A',
        colorLightMarkBg: '#FDEB95',
        colorLightMarkText: '#262626',
        colorLightQuoteBg: '#EAEAEA',
        colorLightQuoteText: '#1A1A1A',
        colorDarkTitleText: '#CCCCCC',
        colorDarkContentText: '#CCCCCC',
        colorDarkContentTextBold: '#CCCCCC',
        colorDarkContentTextItalic: '#CCCCCC',
        colorDarkContentTextCode: '#909090',
        colorDarkLink: '#18BDEC',
        colorDarkLinkExt: '#18BDEC',
        colorDarkTag: '#909090',
        colorDarkUiPanelsBg: '#27272A',
        colorDarkUiBodyBg: '#18181A',
        colorDarkContentBg: '#18181A',
        colorDarkContentPropsBg: '#27272A',
        colorDarkContentAltBg: '#27272A',
        colorDarkH1: '#CCCCCC',
        colorDarkH2: '#CCCCCC',
        colorDarkH3: '#CCCCCC',
        colorDarkH4: '#CCCCCC',
        colorDarkH5: '#CCCCCC',
        colorDarkH6: '#CCCCCC',
        colorDarkMarkBg: '#FCE386',
        colorDarkMarkText: '#262626',
        colorDarkQuoteBg: '#27272A',
        colorDarkQuoteText: '#CCCCCC',
        backgroundURLLight: '',
        backgroundURLDark: '',
        backgroundPadding: '32px 32px 32px 32px',
        backgroundShadow: false,
        bannersAsBackground: false,
        bannersIconGlow: false,
        contentMaxWidth: '940px',
        contentWideMaxWidth: '100%'
    },
    Chocolate: {
        fontContentName: 'Mulish',
        fontContentSize: '17px',
        fontUiSize: '13px',
        colorLightTitleText: '#2D3D43',
        colorLightContentText: '#2D3D43',
        colorLightContentTextBold: '#C26356',
        colorLightContentTextItalic: '#9A6064',
        colorLightContentTextCode: '#9a6064',
        colorLightLink: '#368B96',
        colorLightLinkExt: '#368B96',
        colorLightTag: '#CA7B70',
        colorLightUiPanelsBg: '#E3D6CE',
        colorLightUiBodyBg: '#E9DED8',
        colorLightContentBg: '#E9DED8',
        colorLightContentPropsBg: '#D7D5D1',
        colorLightContentAltBg: '#E5D6D0',
        colorLightH1: '#2D3D43',
        colorLightH2: '#2D3D43',
        colorLightH3: '#2D3D43',
        colorLightH4: '#2D3D43',
        colorLightH5: '#2D3D43',
        colorLightH6: '#2D3D43',
        colorLightMarkBg: '#E5D1CB',
        colorLightMarkText: '#C26256',
        colorLightQuoteBg: '#D9C5C0',
        colorLightQuoteText: '#9A6064',
        colorDarkTitleText: '#B5937D',
        colorDarkContentText: '#B5937D',
        colorDarkContentTextBold: '#D54455',
        colorDarkContentTextItalic: '#C26356',
        colorDarkContentTextCode: '#C26356',
        colorDarkLink: '#56B6C2',
        colorDarkLinkExt: '#56B6C2',
        colorDarkTag: '#B33D4B',
        colorDarkUiPanelsBg: '#34282B',
        colorDarkUiBodyBg: '#2B2124',
        colorDarkContentBg: '#2B2124',
        colorDarkContentPropsBg: '#303134',
        colorDarkContentAltBg: '#34282B',
        colorDarkH1: '#B5937D',
        colorDarkH2: '#B5937D',
        colorDarkH3: '#B5937D',
        colorDarkH4: '#B5937D',
        colorDarkH5: '#B5937D',
        colorDarkH6: '#B5937D',
        colorDarkMarkBg: '#3D2529',
        colorDarkMarkText: '#D54455',
        colorDarkQuoteBg: '#492E2E',
        colorDarkQuoteText: '#C26356',
        backgroundURLLight: 'lsp://logseq.io/logseq-awesome-styler/dist/img/chocolate-bg-light.webp',
        backgroundURLDark: 'lsp://logseq.io/logseq-awesome-styler/dist/img/chocolate-bg-dark.webp',
        backgroundPadding: '20px 40px 20px 40px',
        backgroundShadow: true,
        bannersAsBackground: false,
        bannersIconGlow: false,
        contentMaxWidth: '1100px',
        contentWideMaxWidth: '1600px'
    },
};

export const settingsConfig: SettingSchemaDesc[] = [
    {
        key: 'promoAwesomeLinks',
        title: '',
        description: globals.promoAwesomeLinksMsg,
        type: 'boolean',
        default: false,
    },
    {
        key: 'promoAwesomeUI',
        title: '',
        description: globals.promoAwesomeUIMsg,
        type: 'boolean',
        default: false,
    },
    {
        key: 'presetHeading',
        title: 'Presets',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'presetName',
        title: '⚠ Built-in presets are read-only!',
        description: '(press ">>" button to copy values from predefined preset to your "Custom (1,2,3)")',
        type: 'enum',
        enumPicker: 'select',
        enumChoices: presetsList,
        default: 'Solarized_default',
    },
    {
        key: 'presetCustom',
        title: 'Custom theme configuration',
        description: '',
        type: 'object',
        default: presetsConfig.Solarized_default,
    },
    {
        key: 'presetCustom2',
        title: 'Custom2 theme configuration',
        description: '',
        type: 'object',
        default: presetsConfig.Solarized_default,
    },
    {
        key: 'presetCustom3',
        title: 'Custom3 theme configuration',
        description: '',
        type: 'object',
        default: presetsConfig.Solarized_default,
    },
    {
        key: 'fontHeading',
        title: 'Font',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'fontContentName',
        title: 'Content font name',
        description: '',
        type: 'enum',
        enumPicker: 'select',
        enumChoices: fontsList,
        default: presetsConfig.Solarized_default.fontContentName,
    },
    {
        key: 'fontContentSize',
        title: 'Content font size',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.fontContentSize,
    },
    {
        key: 'fontUiSize',
        title: 'UI font size',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.fontUiSize,
    },
    {
        key: 'colorLightHeading',
        title: 'Colors: light mode (switch to dark to see it`s settings)',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'colorLightUiPanelsBg',
        title: 'UI bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightUiPanelsBg
    },
    {
        key: 'colorLightUiBodyBg',
        title: 'Body bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightUiBodyBg
    },
    {
        key: 'colorLightContentBg',
        title: 'Page bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentBg
    },
    {
        key: 'colorLightContentPropsBg',
        title: 'Props bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentPropsBg
    },
    {
        key: 'colorLightContentAltBg',
        title: 'References bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentAltBg
    },
    {
        key: 'colorLightTitleText',
        title: 'Title',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightTitleText
    },
    {
        key: 'colorLightContentText',
        title: 'Text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentText
    },
    {
        key: 'colorLightContentTextBold',
        title: 'Bold',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentTextBold
    },
    {
        key: 'colorLightContentTextItalic',
        title: 'Italic',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentTextItalic
    },
    {
        key: 'colorLightContentTextCode',
        title: 'Inline code',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentTextCode
    },
    {
        key: 'colorLightLink',
        title: 'Link (internal)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightLink
    },
    {
        key: 'colorLightLinkExt',
        title: 'Link (external)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightLinkExt
    },
    {
        key: 'colorLightTag',
        title: 'Tag',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightTag
    },
    {
        key: 'colorLightH1',
        title: 'H1',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH1
    },
    {
        key: 'colorLightH2',
        title: 'H2',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH2
    },
    {
        key: 'colorLightH3',
        title: 'H3',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH3
    },
    {
        key: 'colorLightH4',
        title: 'H4',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH4
    },
    {
        key: 'colorLightH5',
        title: 'H5',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH5
    },
    {
        key: 'colorLightH6',
        title: 'H6',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH6
    },
    {
        key: 'colorLightMarkBg',
        title: 'Highlight bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightMarkBg
    },
    {
        key: 'colorLightMarkText',
        title: 'Highlight text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightMarkText
    },
    {
        key: 'colorLightQuoteBg',
        title: 'Quote bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightQuoteBg
    },
    {
        key: 'colorLightQuoteText',
        title: 'Quote text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightQuoteText
    },
    {
        key: 'colorDarkHeading',
        title: 'Colors: dark mode (switch to light to see it`s settings)',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'colorDarkUiPanelsBg',
        title: 'UI bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkUiPanelsBg
    },
    {
        key: 'colorDarkUiBodyBg',
        title: 'Body bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkUiBodyBg
    },
    {
        key: 'colorDarkContentBg',
        title: 'Page bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentBg
    },
    {
        key: 'colorDarkContentPropsBg',
        title: 'Props bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentPropsBg
    },
    {
        key: 'colorDarkContentAltBg',
        title: 'References bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentAltBg
    },
    {
        key: 'colorDarkTitleText',
        title: 'Title',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkTitleText
    },
    {
        key: 'colorDarkContentText',
        title: 'Text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentText
    },
    {
        key: 'colorDarkContentTextBold',
        title: 'Bold',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentTextBold
    },
    {
        key: 'colorDarkContentTextItalic',
        title: 'Italic',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentTextItalic
    },
    {
        key: 'colorDarkContentTextCode',
        title: 'Inline code',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentTextCode
    },
    {
        key: 'colorDarkLink',
        title: 'Link (internal)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkLink
    },
    {
        key: 'colorDarkLinkExt',
        title: 'Link (external)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkLinkExt
    },
    {
        key: 'colorDarkTag',
        title: 'Tag',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkTag
    },
    {
        key: 'colorDarkH1',
        title: 'H1',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH1
    },
    {
        key: 'colorDarkH2',
        title: 'H2',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH2
    },
    {
        key: 'colorDarkH3',
        title: 'H3',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH3
    },
    {
        key: 'colorDarkH4',
        title: 'H4',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH4
    },
    {
        key: 'colorDarkH5',
        title: 'H5',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH5
    },
    {
        key: 'colorDarkH6',
        title: 'H6',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH6
    },
    {
        key: 'colorDarkMarkBg',
        title: 'Highlight bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkMarkBg
    },
    {
        key: 'colorDarkMarkText',
        title: 'Highlight text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkMarkText
    },
    {
        key: 'colorDarkQuoteBg',
        title: 'Quote bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkQuoteBg
    },
    {
        key: 'colorDarkQuoteText',
        title: 'Quote text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkQuoteText
    },
    {
        key: 'backgroundHeading',
        title: 'Background (switch to light/dark to see it`s own settings)',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'backgroundURLLight',
        title: 'Background URL (set empty to disable feature)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.backgroundURLLight,
    },
    {
        key: 'backgroundURLDark',
        title: 'Background URL (set empty to disable feature)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.backgroundURLDark,
    },
    {
        key: 'backgroundPadding',
        title: 'Content background padding (top right bottom left)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.backgroundPadding,
    },
    {
        key: 'backgroundShadow',
        title: '',
        description: 'Enable content shadow?',
        type: 'boolean',
        default: presetsConfig.Solarized_default.backgroundShadow
    },
    {
        key: 'bannersPluginHeading',
        title: 'Banners plugin support',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'bannersAsBackground',
        title: '',
        description: 'Use banner image as blurred background?',
        type: 'boolean',
        default: presetsConfig.Solarized_default.bannersAsBackground,
    },
    {
        key: 'bannersIconGlow',
        title: '',
        description: 'Add glow to banner icon?',
        type: 'boolean',
        default: presetsConfig.Solarized_default.bannersIconGlow,
    },
    {
        key: 'sizeHeading',
        title: 'Sizes',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'contentMaxWidth',
        title: 'Content max width (px, %, vw)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.contentMaxWidth,
    },
    {
        key: 'contentWideMaxWidth',
        title: 'Content max width in wide mode (in px, %, vw)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.contentWideMaxWidth,
    },
    {
        key: 'leftSidebarWidth',
        title: 'Left sidebar width (in px, %, vw)',
        description: '',
        type: 'string',
        default: '250px',
    },
    {
        key: 'rightSidebarWidth',
        title: 'Right sidebar width (in px, %, vw)',
        description: '',
        type: 'string',
        default: '460px',
    },
    {
        key: 'otherHeading',
        title: 'Other',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'featureUpdaterEnabled',
        title: '',
        description: 'Enable new version notifier on app load?',
        type: 'boolean',
        default: true,
    },
];
