import { SettingSchemaDesc } from '@logseq/libs/dist/LSPlugin.user';

interface PresetConfig {
    [key: string]: {
        [key: string]: string | number | boolean;
    };
}

export const presetsList: string[] = [
    'Solarized_default',
    'Chocolate',
    'Logseq_original',
    'Mia_quattro',
    'Bear',
    'Nord',
    'Darcula',
    'Custom',
    'Custom2',
    'Custom3'
];

export const fontsList: string[] = [
    'Fira Sans (theme default)',
    'Inter (Logseq default)',
    'Mulish',
    'iA Writer Quattro',
    'OS System default',
    '霞鹜文楷'
];

export const presetsConfig: PresetConfig = {
    Solarized_default: {
        fontContentName: 'Fira Sans (theme default)',
        fontContentSize: '16px',
        fontUiName: 'OS System default',
        fontUiSize: '13px',
        colorLightTitleText: '#009991',
        colorLightContentText: '#354145',
        colorLightContentTextBold: '#354145',
        colorLightContentTextItalic: '#354145',
        colorLightLink: '#009991',
        colorLightLinkExt: '#B88726',
        colorLightTagText: '#FEF8EC',
        colorLightTag: '#5B99B9',
        colorLightUiRSidebarBg: '#EDE4D4',
        colorLightUiLSidebarBg: '#EDE4D4',
        colorLightUiLSidebarBgAccent: '#FEF8EC',
        colorLightUiLSidebarText: '#354145',
        colorLightUiBodyBg: '#F1EBDF',
        colorLightContentBg: '#FEF8EC',
        colorLightContentPropsBg: '#F1EBDF',
        colorLightContentAltBg: '#F0E9DB',
        colorLightH1: '#354145',
        colorLightH2: '#354145',
        colorLightH3: '#354145',
        colorLightH4: '#354145',
        colorLightH5: '#354145',
        colorLightH6: '#354145',
        colorLightMarkBg: '#F9D86C',
        colorLightMarkText: '#354145',
        colorLightQuoteBg: '#D7EADD',
        colorLightQuoteText: '#354145',
        colorLightFlashcardBg: '#FEF8EC',
        colorLightFlashcardText: '#354145',
        colorLightInlineCodeText: '#354145',
        colorLightInlineCodeBg: '#F0E9DB',
        colorDarkTitleText: '#B88726',
        colorDarkContentText: '#AFB6B6',
        colorDarkContentTextBold: '#AFB6B6',
        colorDarkContentTextItalic: '#AFB6B6',
        colorDarkLink: '#B88726',
        colorDarkLinkExt: '#738500',
        colorDarkTagText: '#FFFFFF',
        colorDarkTag: '#3A6E88',
        colorDarkH1: '#AFB6B6',
        colorDarkH2: '#AFB6B6',
        colorDarkH3: '#AFB6B6',
        colorDarkH4: '#AFB6B6',
        colorDarkH5: '#AFB6B6',
        colorDarkH6: '#AFB6B6',
        colorDarkUiLSidebarBg: '#002933',
        colorDarkUiLSidebarBgAccent: '#00323d',
        colorDarkUiLSidebarText: '#AFB6B6',
        colorDarkUiRSidebarBg: '#002933',
        colorDarkUiBodyBg: '#002E38',
        colorDarkContentBg: '#00323d',
        colorDarkContentPropsBg: '#073945',
        colorDarkContentAltBg: '#002E38',
        colorDarkMarkBg: '#F9D86C',
        colorDarkMarkText: '#334247',
        colorDarkQuoteBg: '#223F3F',
        colorDarkQuoteText: '#AFB6B6',
        colorDarkFlashcardBg: '#00323d',
        colorDarkFlashcardText: '#AFB6B6',
        colorDarkInlineCodeText: '#AFB6B6',
        colorDarkInlineCodeBg: '#073945',
        backgroundURLLight: 'lsp://logseq.io/logseq-awesome-styler/dist/img/bg.webp',
        backgroundURLDark: 'lsp://logseq.io/logseq-awesome-styler/dist/img/bg.webp',
    },
    Logseq_original: {
        fontContentName: 'Inter (Logseq default)',
        fontContentSize: '16px',
        fontUiName: 'OS System default',
        fontUiSize: '13px',
        colorLightTitleText: '#433F38',
        colorLightContentText: '#433F38',
        colorLightContentTextBold: '#433F38',
        colorLightContentTextItalic: '#433F38',
        colorLightLink: '#106BA3',
        colorLightLinkExt: '#106BA3',
        colorLightTagText: '#FFFFFF',
        colorLightTag: '#106BA3',
        colorLightUiRSidebarBg: '#F7F7F7',
        colorLightUiLSidebarBg: '#F7F7F7',
        colorLightUiLSidebarBgAccent: '#FFFFFF',
        colorLightUiLSidebarText: '#433F38',
        colorLightUiBodyBg: '#FFFFFF',
        colorLightContentBg: '#FFFFFF',
        colorLightContentPropsBg: '#F7F7F7',
        colorLightContentAltBg: '#F7F7F7',
        colorLightH1: '#433F38',
        colorLightH2: '#433F38',
        colorLightH3: '#433F38',
        colorLightH4: '#433F38',
        colorLightH5: '#433F38',
        colorLightH6: '#433F38',
        colorLightMarkBg: '#FEF3AC',
        colorLightMarkText: '#262626',
        colorLightQuoteBg: '#FBFAF8',
        colorLightQuoteText: '#433F38',
        colorLightFlashcardBg: '#FFFFFF',
        colorLightFlashcardText: '#433F38',
        colorLightInlineCodeText: '#433F38',
        colorLightInlineCodeBg: '#F7F7F7',
        colorDarkTitleText: '#A4B5B6',
        colorDarkContentText: '#A4B5B6',
        colorDarkContentTextBold: '#A4B5B6',
        colorDarkContentTextItalic: '#A4B5B6',
        colorDarkLink: '#8ABBBB',
        colorDarkLinkExt: '#8ABBBB',
        colorDarkTagText: '#262626',
        colorDarkTag: '#8ABBBB',
        colorDarkUiLSidebarBg: '#023643',
        colorDarkUiLSidebarBgAccent: '#002B36',
        colorDarkUiLSidebarText: '#A4B5B6',
        colorDarkUiRSidebarBg: '#023643',
        colorDarkUiBodyBg: '#002B36',
        colorDarkContentBg: '#002B36',
        colorDarkContentPropsBg: '#083643',
        colorDarkContentAltBg: '#083643',
        colorDarkH1: '#A4B5B6',
        colorDarkH2: '#A4B5B6',
        colorDarkH3: '#A4B5B6',
        colorDarkH4: '#A4B5B6',
        colorDarkH5: '#A4B5B6',
        colorDarkH6: '#A4B5B6',
        colorDarkMarkBg: '#FEF4AE',
        colorDarkMarkText: '#262626',
        colorDarkQuoteBg: '#083643',
        colorDarkQuoteText: '#A4B5B6',
        colorDarkFlashcardBg: '#002B36',
        colorDarkFlashcardText: '#A4B5B6',
        colorDarkInlineCodeText: '#A4B5B6',
        colorDarkInlineCodeBg: '#01222A',
        backgroundURLLight: '',
        backgroundURLDark: '',
    },
    Chocolate: {
        fontContentName: 'Mulish',
        fontContentSize: '16px',
        fontUiName: 'OS System default',
        fontUiSize: '13px',
        colorLightTitleText: '#2D3D43',
        colorLightContentText: '#2D3D43',
        colorLightContentTextBold: '#C26356',
        colorLightContentTextItalic: '#9A6064',
        colorLightLink: '#368B96',
        colorLightLinkExt: '#738A8C',
        colorLightTagText: '#E9DED8',
        colorLightTag: '#CA7B70',
        colorLightUiLSidebarBg: '#E1D1C7',
        colorLightUiLSidebarBgAccent: '#E9DED8',
        colorLightUiLSidebarText: '#2D3D43',
        colorLightUiRSidebarBg: '#E1D1C7',
        colorLightUiBodyBg: '#E3D6CE',
        colorLightContentBg: '#E9DED8',
        colorLightContentPropsBg: '#D7D5D1',
        colorLightContentAltBg: '#E3D6CE',
        colorLightH1: '#2D3D43',
        colorLightH2: '#2D3D43',
        colorLightH3: '#2D3D43',
        colorLightH4: '#2D3D43',
        colorLightH5: '#2D3D43',
        colorLightH6: '#2D3D43',
        colorLightMarkBg: '#E5D1CB',
        colorLightMarkText: '#C26256',
        colorLightQuoteBg: '#D9C5C0',
        colorLightQuoteText: '#9A6064',
        colorLightFlashcardBg: '#E9DED8',
        colorLightFlashcardText: '#9A6064',
        colorLightInlineCodeText: '#2D3D43',
        colorLightInlineCodeBg: '#E5D6D0',
        colorDarkTitleText: '#B5937D',
        colorDarkContentText: '#B5937D',
        colorDarkContentTextBold: '#D54455',
        colorDarkContentTextItalic: '#C26356',
        colorDarkLink: '#56B6C2',
        colorDarkLinkExt: '#73898C',
        colorDarkTagText: '#ECE4DF',
        colorDarkTag: '#B33D4B',
        colorDarkUiLSidebarBg: '#34282B',
        colorDarkUiLSidebarBgAccent: '#2B2124',
        colorDarkUiLSidebarText: '#B5937D',
        colorDarkUiRSidebarBg: '#34282B',
        colorDarkUiBodyBg: '#2B2124',
        colorDarkContentBg: '#2B2124',
        colorDarkContentPropsBg: '#303134',
        colorDarkContentAltBg: '#34282B',
        colorDarkH1: '#B5937D',
        colorDarkH2: '#B5937D',
        colorDarkH3: '#B5937D',
        colorDarkH4: '#B5937D',
        colorDarkH5: '#B5937D',
        colorDarkH6: '#B5937D',
        colorDarkMarkBg: '#3D2529',
        colorDarkMarkText: '#D54455',
        colorDarkQuoteBg: '#492E2E',
        colorDarkQuoteText: '#C26356',
        colorDarkFlashcardBg: '#2B2124',
        colorDarkFlashcardText: '#C26356',
        colorDarkInlineCodeText: '#B5937D',
        colorDarkInlineCodeBg: '#34282B',
        backgroundURLLight: 'lsp://logseq.io/logseq-awesome-styler/dist/img/chocolate-bg-light.webp',
        backgroundURLDark: 'lsp://logseq.io/logseq-awesome-styler/dist/img/chocolate-bg-dark.webp',
    },
    Mia_quattro: {
        fontContentName: 'iA Writer Quattro',
        fontContentSize: '16px',
        fontUiName: 'OS System default',
        fontUiSize: '13px',
        colorLightTitleText: '#1A1A1A',
        colorLightContentText: '#1A1A1A',
        colorLightContentTextBold: '#1A1A1A',
        colorLightContentTextItalic: '#1A1A1A',
        colorLightLink: '#0B82B9',
        colorLightLinkExt: '#0B82B9',
        colorLightTagText: '#1A1A1A',
        colorLightTag: '#F7F7F7',
        colorLightUiRSidebarBg: '#EAEAEA',
        colorLightUiLSidebarBg: '#EAEAEA',
        colorLightUiLSidebarBgAccent: '#F7F7F7',
        colorLightUiLSidebarText: '#1A1A1A',
        colorLightUiBodyBg: '#F7F7F7',
        colorLightContentBg: '#F7F7F7',
        colorLightContentPropsBg: '#EAEAEA',
        colorLightContentAltBg: '#EAEAEA',
        colorLightH1: '#1A1A1A',
        colorLightH2: '#1A1A1A',
        colorLightH3: '#1A1A1A',
        colorLightH4: '#1A1A1A',
        colorLightH5: '#1A1A1A',
        colorLightH6: '#1A1A1A',
        colorLightMarkBg: '#FDEB95',
        colorLightMarkText: '#262626',
        colorLightQuoteBg: '#EAEAEA',
        colorLightQuoteText: '#1A1A1A',
        colorLightFlashcardBg: '#F7F7F7',
        colorLightFlashcardText: '#1A1A1A',
        colorLightInlineCodeText: '#1A1A1A',
        colorLightInlineCodeBg: '#EAEAEA',
        colorDarkTitleText: '#CCCCCC',
        colorDarkContentText: '#CCCCCC',
        colorDarkContentTextBold: '#CCCCCC',
        colorDarkContentTextItalic: '#CCCCCC',
        colorDarkLink: '#18BDEC',
        colorDarkLinkExt: '#18BDEC',
        colorDarkTagText: '#CCCCCC',
        colorDarkTag: '#18181A',
        colorDarkUiLSidebarBg: '#27272A',
        colorDarkUiLSidebarBgAccent: '#18181A',
        colorDarkUiLSidebarText: '#CCCCCC',
        colorDarkUiRSidebarBg: '#27272A',
        colorDarkUiBodyBg: '#18181A',
        colorDarkContentBg: '#18181A',
        colorDarkContentPropsBg: '#27272A',
        colorDarkContentAltBg: '#27272A',
        colorDarkH1: '#CCCCCC',
        colorDarkH2: '#CCCCCC',
        colorDarkH3: '#CCCCCC',
        colorDarkH4: '#CCCCCC',
        colorDarkH5: '#CCCCCC',
        colorDarkH6: '#CCCCCC',
        colorDarkMarkBg: '#FCE386',
        colorDarkMarkText: '#262626',
        colorDarkQuoteBg: '#27272A',
        colorDarkQuoteText: '#CCCCCC',
        colorDarkFlashcardBg: '#18181A',
        colorDarkFlashcardText: '#CCCCCC',
        colorDarkInlineCodeText: '#CCCCCC',
        colorDarkInlineCodeBg: '#27272A',
        backgroundURLLight: '',
        backgroundURLDark: '',
    },
    Bear: {
        fontContentName: 'Mulish',
        fontContentSize: '16px',
        fontUiName: 'OS System default',
        fontUiSize: '14px',
        colorLightTitleText: '#2E3234',
        colorLightContentText: '#2E3234',
        colorLightContentTextBold: '#2E3234',
        colorLightContentTextItalic: '#2E3234',
        colorLightLink: '#CF4444',
        colorLightLinkExt: '#CF4444',
        colorLightTagText: '#FFFFFF',
        colorLightTag: '#A3A3A3',
        colorLightUiRSidebarBg: '#FBFBFB',
        colorLightUiLSidebarBg: '#2E3234',
        colorLightUiLSidebarBgAccent: '#CF4444',
        colorLightUiLSidebarText: '#CFCFCF',
        colorLightUiBodyBg: '#FBFBFB',
        colorLightContentBg: '#FBFBFB',
        colorLightContentPropsBg: '#F7F7F7',
        colorLightContentAltBg: '#FFFFFF',
        colorLightH1: '#2E3234',
        colorLightH2: '#2E3234',
        colorLightH3: '#2E3234',
        colorLightH4: '#2E3234',
        colorLightH5: '#2E3234',
        colorLightH6: '#2E3234',
        colorLightMarkBg: '#FEF3AC',
        colorLightMarkText: '#2E3234',
        colorLightQuoteBg: '#E4ECF8',
        colorLightQuoteText: '#2E3234',
        colorLightFlashcardBg: '#FBFBFB',
        colorLightFlashcardText: '#2E3234',
        colorLightInlineCodeText: '#2E3234',
        colorLightInlineCodeBg: '#FFFFFF',
        colorDarkTitleText: '#EFF1F5',
        colorDarkContentText: '#EFF1F5',
        colorDarkContentTextBold: '#EFF1F5',
        colorDarkContentTextItalic: '#EFF1F5',
        colorDarkLink: '#F5C662',
        colorDarkLinkExt: '#F5C662',
        colorDarkTagText: '#FFFFFF',
        colorDarkTag: '#7A7C7F',
        colorDarkUiLSidebarBg: '#1E232F',
        colorDarkUiLSidebarBgAccent: '#F5C662',
        colorDarkUiLSidebarText: '#B1BACD',
        colorDarkUiRSidebarBg: '#282F3E',
        colorDarkUiBodyBg: '#282F3E',
        colorDarkContentBg: '#282F3E',
        colorDarkContentPropsBg: '#262D3B',
        colorDarkContentAltBg: '#262D3B',
        colorDarkH1: '#EFF1F5',
        colorDarkH2: '#EFF1F5',
        colorDarkH3: '#EFF1F5',
        colorDarkH4: '#EFF1F5',
        colorDarkH5: '#EFF1F5',
        colorDarkH6: '#EFF1F5',
        colorDarkMarkBg: '#FEF3AC',
        colorDarkMarkText: '#262626',
        colorDarkQuoteBg: '#293950',
        colorDarkQuoteText: '#EFF1F5',
        colorDarkFlashcardBg: '#282F3E',
        colorDarkFlashcardText: '#EFF1F5',
        colorDarkInlineCodeText: '#EFF1F5',
        colorDarkInlineCodeBg: '#1E232F',
    },
    Nord: {
        fontContentName: 'Fira Sans (theme default)',
        fontContentSize: '16px',
        fontUiName: 'OS System default',
        fontUiSize: '13px',
        colorLightTitleText: '#5E81AC',
        colorLightContentText: '#3B4252',
        colorLightContentTextBold: '#3B4252',
        colorLightContentTextItalic: '#3B4252',
        colorLightLink: '#81A1C1',
        colorLightLinkExt: '#8FBCBB',
        colorLightTagText: '#ECEFF4',
        colorLightTag: '#5E81AC',
        colorLightUiLSidebarBg: '#E5E9F0',
        colorLightUiLSidebarText: '#3B4252',
        colorLightUiLSidebarBgAccent: '#81A1C1',
        colorLightUiRSidebarBg: '#ECEFF4',
        colorLightUiBodyBg: '#ECEFF4',
        colorLightContentBg: '#ECEFF4',
        colorLightContentPropsBg: '#E5E9F0',
        colorLightContentAltBg: '#E5E9F0',
        colorLightH1: '#3B4252',
        colorLightH2: '#3B4252',
        colorLightH3: '#3B4252',
        colorLightH4: '#3B4252',
        colorLightH5: '#3B4252',
        colorLightH6: '#3B4252',
        colorLightMarkBg: '#EBCB8B',
        colorLightMarkText: '#3B4252',
        colorLightQuoteBg: '#D8DEE9',
        colorLightQuoteText: '#3B4252',
        colorLightFlashcardBg: '#ECEFF4',
        colorLightFlashcardText: '#3B4252',
        colorLightInlineCodeBg: '#D8DEE9',
        colorLightInlineCodeText: '#3B4252',
        colorDarkTitleText: '#5E81AC',
        colorDarkContentText: '#D8DEE9',
        colorDarkContentTextBold: '#D8DEE9',
        colorDarkContentTextItalic: '#D8DEE9',
        colorDarkLink: '#81A1C1',
        colorDarkLinkExt: '#8FBCBB',
        colorDarkTagText: '#ECEFF4',
        colorDarkTag: '#5E81AC',
        colorDarkUiLSidebarBg: '#3B4252',
        colorDarkUiLSidebarText: '#D8DEE9',
        colorDarkUiLSidebarBgAccent: '#81A1C1',
        colorDarkUiRSidebarBg: '#2E3440',
        colorDarkUiBodyBg: '#2E3440',
        colorDarkContentBg: '#2E3440',
        colorDarkContentPropsBg: '#3B4252',
        colorDarkContentAltBg: '#3B4252',
        colorDarkH1: '#D8DEE9',
        colorDarkH2: '#D8DEE9',
        colorDarkH3: '#D8DEE9',
        colorDarkH4: '#D8DEE9',
        colorDarkH5: '#D8DEE9',
        colorDarkH6: '#D8DEE9',
        colorDarkMarkBg: '#EBCB8B',
        colorDarkMarkText: '#3B4252',
        colorDarkQuoteBg: '#4C566A',
        colorDarkQuoteText: '#D8DEE9',
        colorDarkFlashcardBg: '#2E3440',
        colorDarkFlashcardText: '#D8DEE9',
        colorDarkInlineCodeBg: '#3B4252',
        colorDarkInlineCodeText: '#D8DEE9',
        backgroundURLLight: '',
        backgroundURLDark: '',
    },
    Darcula: {
        fontContentName: 'OS System default',
        fontContentSize: '16px',
        fontUiName: 'OS System default',
        fontUiSize: '13px',
        colorLightTitleText: '#C13F8E',
        colorLightContentText: '#282A36',
        colorLightContentTextBold: '#282A36',
        colorLightContentTextItalic: '#282A36',
        colorLightLink: '#855FBF',
        colorLightLinkExt: '#007E90',
        colorLightTagText: '#F8F8F2',
        colorLightTag: '#A0651B',
        colorLightUiLSidebarBg: '#E1E1DB',
        colorLightUiLSidebarText: '#282A36',
        colorLightUiLSidebarBgAccent: '#BD93F9',
        colorLightUiRSidebarBg: '#F8F8F2',
        colorLightUiBodyBg: '#F8F8F2',
        colorLightContentBg: '#F8F8F2',
        colorLightContentPropsBg: '#EAEAE5',
        colorLightContentAltBg: '#EAEAE5',
        colorLightH1: '#C13F8E',
        colorLightH2: '#C13F8E',
        colorLightH3: '#C13F8E',
        colorLightH4: '#C13F8E',
        colorLightH5: '#C13F8E',
        colorLightH6: '#C13F8E',
        colorLightMarkBg: '#F1FA8C',
        colorLightMarkText: '#282A36',
        colorLightQuoteBg: '#B6BCCE',
        colorLightQuoteText: '#f8f8f2',
        colorLightFlashcardBg: '#F8F8F2',
        colorLightFlashcardText: '#282A36',
        colorLightInlineCodeText: '#282a36',
        colorLightInlineCodeBg: '#F8F8F2',
        colorDarkTitleText: '#FF79C6',
        colorDarkContentText: '#E6E6E6',
        colorDarkContentTextBold: '#BDBDBD',
        colorDarkContentTextItalic: '#E6E6E6',
        colorDarkLink: '#BD93F9',
        colorDarkLinkExt: '#7DD4E8',
        colorDarkTagText: '#282A36',
        colorDarkTag: '#FFB86C',
        colorDarkUiLSidebarBg: '#323545',
        colorDarkUiLSidebarText: '#A2ADB8',
        colorDarkUiLSidebarBgAccent: '#BD93F9',
        colorDarkUiRSidebarBg: '#323545',
        colorDarkUiBodyBg: '#272A36',
        colorDarkContentBg: '#272A36',
        colorDarkContentPropsBg: '#323341',
        colorDarkContentAltBg: '#323341',
        colorDarkH1: '#FF79C6',
        colorDarkH2: '#FF79C6',
        colorDarkH3: '#FF79C6',
        colorDarkH4: '#FF79C6',
        colorDarkH5: '#FF79C6',
        colorDarkH6: '#FF79C6',
        colorDarkMarkBg: '#F1FA8C',
        colorDarkMarkText: '#44475A',
        colorDarkQuoteBg: '#323341',
        colorDarkQuoteText: '#E6E6E6',
        colorDarkFlashcardBg: '#272A36',
        colorDarkFlashcardText: '#E6E6E6',
        colorDarkInlineCodeBg: '#323545',
        colorDarkInlineCodeText: '#E6E6E6',
        backgroundURLLight: '',
        backgroundURLDark: '',
    },
};

export const settingsConfig: SettingSchemaDesc[] = [
    {
        key: 'presetHeading',
        title: 'Presets',
        description: 'Built-in themes + 3 custom slots',
        type: 'heading',
        default: null,
    },
    {
        key: 'presetName',
        title: '⚠ Built-in presets are read-only!',
        description: '(press ">>" button to copy values from predefined preset to your "Custom (1,2,3)")',
        type: 'enum',
        enumPicker: 'select',
        enumChoices: presetsList,
        default: 'Solarized_default',
    },
    {
        key: 'presetCustom',
        title: 'Custom theme configuration',
        description: '',
        type: 'object',
        default: presetsConfig.Solarized_default,
    },
    {
        key: 'presetCustom2',
        title: 'Custom2 theme configuration',
        description: '',
        type: 'object',
        default: presetsConfig.Solarized_default,
    },
    {
        key: 'presetCustom3',
        title: 'Custom3 theme configuration',
        description: '',
        type: 'object',
        default: presetsConfig.Solarized_default,
    },
    {
        key: 'fontHeading',
        title: 'Font',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'fontContentName',
        title: 'Content font name',
        description: '',
        type: 'enum',
        enumPicker: 'select',
        enumChoices: fontsList,
        default: presetsConfig.Solarized_default.fontContentName,
    },
    {
        key: 'fontContentSize',
        title: 'Content font size',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.fontContentSize,
    },
    {
        key: 'fontUiName',
        title: 'UI font name',
        description: '',
        type: 'enum',
        enumPicker: 'select',
        enumChoices: fontsList,
        default: presetsConfig.Solarized_default.fontUiName,
    },
    {
        key: 'fontUiSize',
        title: 'UI font size',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.fontUiSize,
    },
    {
        key: 'colorLightHeading',
        title: 'Colors',
        description: 'light mode (switch to dark to see it`s settings)',
        type: 'heading',
        default: null,
    },
    {
        key: 'colorLightUiLSidebarBg',
        title: 'Left sidebar background',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightUiLSidebarBg
    },
    {
        key: 'colorLightUiLSidebarText',
        title: 'Left sidebar text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightUiLSidebarText
    },
    {
        key: 'colorLightUiLSidebarBgAccent',
        title: 'Left sidebar accent',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightUiLSidebarBgAccent
    },
    {
        key: 'colorLightUiRSidebarBg',
        title: 'Right sidebar background',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightUiRSidebarBg
    },
    {
        key: 'colorLightUiBodyBg',
        title: 'Body bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightUiBodyBg
    },
    {
        key: 'colorLightContentBg',
        title: 'Content bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentBg
    },
    {
        key: 'colorLightContentPropsBg',
        title: 'Props bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentPropsBg
    },
    {
        key: 'colorLightContentAltBg',
        title: 'References bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentAltBg
    },
    {
        key: 'colorLightTitleText',
        title: 'Page title',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightTitleText
    },
    {
        key: 'colorLightContentText',
        title: 'Text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentText
    },
    {
        key: 'colorLightContentTextBold',
        title: 'Bold',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentTextBold
    },
    {
        key: 'colorLightContentTextItalic',
        title: 'Italic',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightContentTextItalic
    },
    {
        key: 'colorLightLink',
        title: 'Link (internal)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightLink
    },
    {
        key: 'colorLightLinkExt',
        title: 'Link (external)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightLinkExt
    },
    {
        key: 'colorLightTagText',
        title: 'Tag text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightTagText
    },
    {
        key: 'colorLightTag',
        title: 'Tag bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightTag
    },
    {
        key: 'colorLightH1',
        title: 'H1',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH1
    },
    {
        key: 'colorLightH2',
        title: 'H2',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH2
    },
    {
        key: 'colorLightH3',
        title: 'H3',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH3
    },
    {
        key: 'colorLightH4',
        title: 'H4',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH4
    },
    {
        key: 'colorLightH5',
        title: 'H5',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH5
    },
    {
        key: 'colorLightH6',
        title: 'H6',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightH6
    },
    {
        key: 'colorLightMarkBg',
        title: 'Highlight bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightMarkBg
    },
    {
        key: 'colorLightMarkText',
        title: 'Highlight text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightMarkText
    },
    {
        key: 'colorLightQuoteBg',
        title: 'Quote bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightQuoteBg
    },
    {
        key: 'colorLightQuoteText',
        title: 'Quote text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightQuoteText
    },
    {
        key: 'colorLightFlashcardBg',
        title: 'Flashcard bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightFlashcardBg
    },
    {
        key: 'colorLightFlashcardText',
        title: 'Flashcard text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightFlashcardText
    },
    {
        key: 'colorLightInlineCodeBg',
        title: 'Code bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightInlineCodeBg
    },
    {
        key: 'colorLightInlineCodeText',
        title: 'Code text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorLightInlineCodeText
    },
    {
        key: 'colorDarkHeading',
        title: 'Colors',
        description: 'dark mode (switch to light to see it`s settings)',
        type: 'heading',
        default: null,
    },
    {
        key: 'colorDarkUiLSidebarBg',
        title: 'Left sidebar background',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkUiLSidebarBg
    },
    {
        key: 'colorDarkUiLSidebarText',
        title: 'Left sidebar text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkUiLSidebarText
    },
    {
        key: 'colorDarkUiLSidebarBgAccent',
        title: 'Left sidebar accent',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkUiLSidebarBgAccent
    },
    {
        key: 'colorDarkUiRSidebarBg',
        title: 'Right sidebar background',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkUiRSidebarBg
    },
    {
        key: 'colorDarkUiBodyBg',
        title: 'Body bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkUiBodyBg
    },
    {
        key: 'colorDarkContentBg',
        title: 'Content bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentBg
    },
    {
        key: 'colorDarkContentPropsBg',
        title: 'Props bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentPropsBg
    },
    {
        key: 'colorDarkContentAltBg',
        title: 'References bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentAltBg
    },
    {
        key: 'colorDarkTitleText',
        title: 'Page title',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkTitleText
    },
    {
        key: 'colorDarkContentText',
        title: 'Text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentText
    },
    {
        key: 'colorDarkContentTextBold',
        title: 'Bold',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentTextBold
    },
    {
        key: 'colorDarkContentTextItalic',
        title: 'Italic',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkContentTextItalic
    },
    {
        key: 'colorDarkLink',
        title: 'Link (internal)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkLink
    },
    {
        key: 'colorDarkLinkExt',
        title: 'Link (external)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkLinkExt
    },
    {
        key: 'colorDarkTagText',
        title: 'Tag text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkTagText
    },
    {
        key: 'colorDarkTag',
        title: 'Tag bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkTag
    },
    {
        key: 'colorDarkH1',
        title: 'H1',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH1
    },
    {
        key: 'colorDarkH2',
        title: 'H2',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH2
    },
    {
        key: 'colorDarkH3',
        title: 'H3',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH3
    },
    {
        key: 'colorDarkH4',
        title: 'H4',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH4
    },
    {
        key: 'colorDarkH5',
        title: 'H5',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH5
    },
    {
        key: 'colorDarkH6',
        title: 'H6',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkH6
    },
    {
        key: 'colorDarkMarkBg',
        title: 'Highlight bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkMarkBg
    },
    {
        key: 'colorDarkMarkText',
        title: 'Highlight text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkMarkText
    },
    {
        key: 'colorDarkQuoteBg',
        title: 'Quote bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkQuoteBg
    },
    {
        key: 'colorDarkQuoteText',
        title: 'Quote text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkQuoteText
    },
    {
        key: 'colorDarkFlashcardBg',
        title: 'Flashcard bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkFlashcardBg
    },
    {
        key: 'colorDarkFlashcardText',
        title: 'Flashcard text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkFlashcardText
    },
    {
        key: 'colorDarkInlineCodeBg',
        title: 'Code bg',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkInlineCodeBg
    },
    {
        key: 'colorDarkInlineCodeText',
        title: 'Code text',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.colorDarkInlineCodeText
    },
    {
        key: 'backgroundHeading',
        title: 'Background image',
        description: 'switch to light/dark to see it`s own settings',
        type: 'heading',
        default: null,
    },
    {
        key: 'backgroundURLLight',
        title: 'Background URL (set empty to disable feature)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.backgroundURLLight,
    },
    {
        key: 'backgroundURLDark',
        title: 'Background URL (set empty to disable feature)',
        description: '',
        type: 'string',
        default: presetsConfig.Solarized_default.backgroundURLDark,
    },
    {
        key: 'bannersPluginHeading',
        title: 'Banners plugin support',
        description: 'Install plugin https://github.com/yoyurec/logseq-banners-plugin',
        type: 'heading',
        default: null,
    },
    {
        key: 'bannersAsBackground',
        title: '',
        description: 'Use banner image as blurred background?',
        type: 'boolean',
        default: false,
    },
    {
        key: 'bannersIconGlow',
        title: '',
        description: 'Add glow to banner icon?',
        type: 'boolean',
        default: false,
    },
    {
        key: 'sizeHeading',
        title: 'Sizes',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'contentMaxWidth',
        title: 'Content max width (px, %, vw)',
        description: '',
        type: 'string',
        default: '1100px',
    },
    {
        key: 'contentWideMaxWidth',
        title: 'Content max width in wide mode (in px, %, vw)',
        description: '',
        type: 'string',
        default: '100%',
    },
    {
        key: 'leftSidebarWidth',
        title: 'Left sidebar width (in px, %, vw)',
        description: '',
        type: 'string',
        default: '250px',
    },
    {
        key: 'rightSidebarWidth',
        title: 'Right sidebar width (in px, %, vw)',
        description: '',
        type: 'string',
        default: '420px',
    },
    {
        key: 'otherHeading',
        title: 'Other',
        description: '',
        type: 'heading',
        default: null,
    },
    {
        key: 'featureUpdaterEnabled',
        title: '',
        description: 'Enable new version notifier on app load?',
        type: 'boolean',
        default: true,
    },
];
